name: Awesome-LLM4Code

on:
  schedule:
    - cron: '0 16 * * 3'  # 每周三 UTC 时间 16:00 运行 (中国周四 00:00)
  workflow_dispatch:  # 允许手动触发
permissions:
  contents: write
  pull-requests: write

jobs:
  analyze-papers:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'  # 启用pip缓存
    
    - name: Cache papers directory
      uses: actions/cache@v3
      with:
        path: papers
        key: ${{ runner.os }}-papers-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-papers-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run paper analysis
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        KIMI_API_KEY: ${{ secrets.KIMI_API_KEY }}
      run: |
        cd src
        python main.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GH_TOKEN }}
        commit-message: "Update paper analysis"
        title: "Update paper analysis"
        body: |
          自动更新论文分析结果
          - 更新 archive 目录
          - 更新 README.md
        branch: auto-paper-analysis
        base: main
        delete-branch: true
