name: Awesome-LLM4Code

on:
  schedule:
    - cron: '0 0 * * 4'  # 每周四 UTC 时间 00:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  analyze-papers:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'  # 启用pip缓存
    
    - name: Cache papers directory
      uses: actions/cache@v3
      with:
        path: papers
        key: ${{ runner.os }}-papers-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-papers-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run paper analysis
      env:
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd src
        python main.py
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GH_TOKEN }}
        commit-message: "Update paper analysis $(date +'%Y-%m-%d')"
        title: "Update paper analysis"
        body: |
          自动更新论文分析结果
          - 更新 archive 目录
          - 更新 README.md
        branch: auto-paper-analysis
        base: main
        delete-branch: true
